day4

In [ ]:
import pandas as pd
data=[10,20,30,40,50]
a=pd.Series(data)
print(a)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
import pandas as pd
data=[10,20,30,40,50]
label=("Apple","banana","mango","pineapple","orange")
b=pd.Series(data=label,index=data)
print(b)

10        Apple
20       banana
30        mango
40    pineapple
50       orange
dtype: str

In [ ]:
import pandas as pd
d={"name":"ashish","age":20,"dept":"cse","salary":100000}
b=pd.Series(d)
print(b)

name      ashish
age           20
dept         cse
salary    100000
dtype: object

In [ ]:
import pandas as pd
d={"name":"ashish","age":20,"dept":"cse","salary":100000}
E={"name":"aryan","age":20,"dept":"cse"}
f=pd.DataFrame((d,E))
print(f)

     name  age dept    salary
0  ashish   20  cse  100000.0
1   aryan   20  cse       NaN

In [ ]:
import pandas as pd
d={"name":["ashish","aryan","ranjan"],
   "age":[20,21,22],
   "dept":["cse","mech","ece"],
   "salary":[100000,100001,100002]}
f=pd.DataFrame(d)
print(f)

     name  age  dept  salary
0  ashish   20   cse  100000
1   aryan   21  mech  100001
2  ranjan   22   ece  100002

In [ ]:
import pandas as pd
d={"name":["ashish","aryan","ranjan"],
   "age":[20,21,22],
   "dept":["cse","mech","ece"],
   "salary":[100000,100001,100002]}
print(pd.DataFrame(d).loc[0:2])

     name  age  dept  salary
0  ashish   20   cse  100000
1   aryan   21  mech  100001
2  ranjan   22   ece  100002

In [ ]:
import pandas as pd
d={"name":["ashish","aryan","ranjan"],
   "age":[20,21,22],
   "dept":["cse","mech","ece"],
   "salary":[100000,100001,100002]}
print(pd.DataFrame(d).iloc[0:2])

     name  age  dept  salary
0  ashish   20   cse  100000
1   aryan   21  mech  100001

In [ ]:
from pathlib import Path
file_path=Path(r"C:\Users\Ashish\OneDrive\Desktop\filehandling.txt")
file_path

WindowsPath('C:/Users/Ashish/OneDrive/Desktop/filehandling.txt')

In [ ]:
with open(file_path) as simple_file:
    for line in simple_file:
        print(line)

name  age  dept  salary

0  ashish   20   cse  100000

1   aryan   21  mech  100001

In [ ]:
simple_file.close()

In [ ]:
new_path=Path(r"C:\Users\Ashish\OneDrive\Desktop\filehandling.txt")

In [ ]:
with open(new_path,"w",encoding="utf-8") as simple_file:
    simple_file.write("how are you? Are you fine")

In [ ]:
with open(new_path) as simple_file:
    for line in simple_file:
        print(line)

how are you? Are you fine

In [ ]:
if new_path.exists():
    print("True")
else:
    print("This file is not found")

True

In [3]:
import pandas as pd
%pip install openpyxl

df = pd.read_excel(
    r"C:\Users\tuf\Downloads\Amazon_Sales_Power_Query_Day_2.xlsx",
    engine="openpyxl"
)

Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError('A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.'))) - skipping
Requirement already satisfied: openpyxl in c:\Users\tuf\anaconda3\Lib\site-packages (3.1.5)
Requirement already satisfied: et_xmlfile in c:\Users\tuf\anaconda3\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
df

,Order ID,Order Date,Store / Seller,Customer ID,Salesperson,Product,Category,City,Region,Quantity,Unit Price,Discount %,Gross Amount,Sales Amount,Payment Method,Order Status,Sales Channel,Ship Date
0,ORD10001,08-07-2026,Amazon Kochi,CUST1021,Vijay,Wireless Mouse,Electronics,Kochi,South,4.0,799.0,20.0,3196,2556.80,Credit Card,Delivered,Amazon Fresh,13-07-2026
1,ORD10002,22-07-2026,Amazon Coimbatore,CUST1002,Meena,Bluetooth Headphones,Electronics,Coimbatore,South,5.0,1499.0,15.0,7495,6370.75,Net Banking,Returned,Amazon Business,27-07-2026
2,ORD10003,12-07-2026,Amazon Bengaluru,CUST1022,Karthik,Laptop Stand,Office,Bengaluru,South,4.0,1199.0,20.0,4796,3836.80,Net Banking,Delivered,Amazon.in,14-07-2026
3,ORD10004,13-08-2026,Amazon Trichy,CUST1057,Rahul,USB-C Cable,Electronics,Trichy,South,4.0,499.0,15.0,1996,1696.60,Cash on Delivery,Delivered,Amazon Fresh,17-08-2026
4,ORD10005,25-07-2026,Amazon Pune,CUST1014,Priya,Mechanical Keyboard,Electronics,Pune,West,1.0,2549.0,5.0,2549,2421.55,Credit Card,Delivered,Amazon Business,29-07-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,ORD10149,17-07-2026,Amazon Trichy,CUST1032,Rahul,Monitor,Electronics,Trichy,South,3.0,12499.0,5.0,37497,35622.15,Cash on Delivery,Cancelled,Amazon Fresh,20-07-2026
149,ORD10150,03-08-2026,Amazon Madurai,CUST1041,Meena,Coffee Mug,Home,Madurai,South,1.0,499.0,15.0,499,424.15,Debit Card,Delivered,Amazon.in,06-08-2026
150,ORD10011,28-07-2026,Amazon Pune,CUST1008,Sneha,Power Bank,Electronics,Pune,West,2.0,1699.0,5.0,3398,3228.10,Credit Card,Delivered,Amazon Fresh,29-07-2026
151,ORD10026,05-07-2026,Amazon Bengaluru,CUST1032,Rahul,Power Bank,Electronics,Bengaluru,South,1.0,1849.0,25.0,1849,1386.75,UPI,Delivered,Amazon Fresh,10-07-2026
152,ORD10071,10-07-2026,Amazon Pune,CUST1017,Karthik,Power Bank,Electronics,Pune,West,5.0,1799.0,20.0,8995,7196.00,UPI,Returned,Amazon.in,13-07-2026

In [5]:
df.head(100)

,Order ID,Order Date,Store / Seller,Customer ID,Salesperson,Product,Category,City,Region,Quantity,Unit Price,Discount %,Gross Amount,Sales Amount,Payment Method,Order Status,Sales Channel,Ship Date
0,ORD10001,08-07-2026,Amazon Kochi,CUST1021,Vijay,Wireless Mouse,Electronics,Kochi,South,4.0,799.0,20.0,3196,2556.80,Credit Card,Delivered,Amazon Fresh,13-07-2026
1,ORD10002,22-07-2026,Amazon Coimbatore,CUST1002,Meena,Bluetooth Headphones,Electronics,Coimbatore,South,5.0,1499.0,15.0,7495,6370.75,Net Banking,Returned,Amazon Business,27-07-2026
2,ORD10003,12-07-2026,Amazon Bengaluru,CUST1022,Karthik,Laptop Stand,Office,Bengaluru,South,4.0,1199.0,20.0,4796,3836.80,Net Banking,Delivered,Amazon.in,14-07-2026
3,ORD10004,13-08-2026,Amazon Trichy,CUST1057,Rahul,USB-C Cable,Electronics,Trichy,South,4.0,499.0,15.0,1996,1696.60,Cash on Delivery,Delivered,Amazon Fresh,17-08-2026
4,ORD10005,25-07-2026,Amazon Pune,CUST1014,Priya,Mechanical Keyboard,Electronics,Pune,West,1.0,2549.0,5.0,2549,2421.55,Credit Card,Delivered,Amazon Business,29-07-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,ORD10096,03-08-2026,Amazon Bengaluru,CUST1035,Rahul,Office Chair,Furniture,Bengaluru,South,5.0,8899.0,10.0,44495,40045.50,UPI,Returned,Amazon.in,07-08-2026
96,ORD10097,14-07-2026,Amazon Coimbatore,CUST1030,Rahul,Notebook,Stationery,Coimbatore,South,NaN,299.0,0.0,897,897.00,Cash on Delivery,Cancelled,Amazon.in,18-07-2026
97,ORD10098,04-07-2026,Amazon Hyderabad,CUST1045,Priya,Water Bottle,Home,Hyderabad,South,3.0,699.0,25.0,2097,1572.75,UPI,Delivered,Amazon Fresh,05-07-2026
98,ORD10099,23-07-2026,Amazon Coimbatore,CUST1025,Arun,Backpack,Bags,Coimbatore,South,3.0,1499.0,20.0,4497,3597.60,UPI,Delivered,Amazon Business,24-07-2026
99,ORD10100,07-07-2026,Amazon Pune,CUST1008,Priya,Desk Lamp,Home,Pune,West,3.0,1199.0,10.0,3597,3237.30,Net Banking,Cancelled,Amazon.in,10-07-2026

In [6]:
df.tail()

,Order ID,Order Date,Store / Seller,Customer ID,Salesperson,Product,Category,City,Region,Quantity,Unit Price,Discount %,Gross Amount,Sales Amount,Payment Method,Order Status,Sales Channel,Ship Date
148,ORD10149,17-07-2026,Amazon Trichy,CUST1032,Rahul,Monitor,Electronics,Trichy,South,3.0,12499.0,5.0,37497,35622.15,Cash on Delivery,Cancelled,Amazon Fresh,20-07-2026
149,ORD10150,03-08-2026,Amazon Madurai,CUST1041,Meena,Coffee Mug,Home,Madurai,South,1.0,499.0,15.0,499,424.15,Debit Card,Delivered,Amazon.in,06-08-2026
150,ORD10011,28-07-2026,Amazon Pune,CUST1008,Sneha,Power Bank,Electronics,Pune,West,2.0,1699.0,5.0,3398,3228.10,Credit Card,Delivered,Amazon Fresh,29-07-2026
151,ORD10026,05-07-2026,Amazon Bengaluru,CUST1032,Rahul,Power Bank,Electronics,Bengaluru,South,1.0,1849.0,25.0,1849,1386.75,UPI,Delivered,Amazon Fresh,10-07-2026
152,ORD10071,10-07-2026,Amazon Pune,CUST1017,Karthik,Power Bank,Electronics,Pune,West,5.0,1799.0,20.0,8995,7196.00,UPI,Returned,Amazon.in,13-07-2026

In [7]:
df.tail(20)

,Order ID,Order Date,Store / Seller,Customer ID,Salesperson,Product,Category,City,Region,Quantity,Unit Price,Discount %,Gross Amount,Sales Amount,Payment Method,Order Status,Sales Channel,Ship Date
133,ORD10134,06-08-2026,Amazon Delhi,CUST1059,Rahul,Monitor,Electronics,Delhi,NaN,2.0,12499.0,15.0,24998,21248.30,UPI,Cancelled,Amazon.in,10-08-2026
134,ORD10135,16-07-2026,Amazon Trichy,CUST1008,Vijay,Coffee Mug,Home,Trichy,South,1.0,449.0,0.0,449,449.00,Cash on Delivery,Delivered,Amazon Fresh,19-07-2026
135,ORD10136,12-07-2026,Amazon Pune,CUST1026,Arun,Wireless Mouse,Electronics,Pune,West,1.0,699.0,5.0,699,664.05,Cash on Delivery,Delivered,Amazon Fresh,15-07-2026
136,ORD10137,22-07-2026,Amazon Trichy,CUST1007,Divya,Bluetooth Headphones,Electronics,Trichy,South,1.0,1599.0,5.0,1599,1519.05,Cash on Delivery,Delivered,Amazon Fresh,24-07-2026
137,ORD10138,18-07-2026,Amazon Coimbatore,CUST1039,Rahul,Laptop Stand,Office,Coimbatore,South,2.0,1399.0,10.0,2798,2518.20,Credit Card,Delivered,Amazon Business,22-07-2026
138,ORD10139,13-08-2026,Amazon Kochi,CUST1045,Priya,USB-C Cable,Electronics,Kochi,South,1.0,499.0,25.0,499,374.25,Debit Card,Cancelled,Amazon Fresh,17-08-2026
139,ORD10140,04-07-2026,Amazon Coimbatore,CUST1022,Arun,Mechanical Keyboard,Electronics,Coimbatore,South,2.0,2399.0,15.0,4798,4078.30,Cash on Delivery,Delivered,Amazon.in,09-07-2026
140,ORD10141,24-08-2026,Amazon Trichy,CUST1042,Priya,Office Chair,Furniture,Trichy,South,4.0,8999.0,25.0,35996,26997.00,Debit Card,Cancelled,Amazon.in,27-08-2026
141,ORD10142,29-07-2026,Amazon Bengaluru,CUST1029,Divya,Notebook,Stationery,Bengaluru,South,3.0,249.0,10.0,747,672.30,Cash on Delivery,Shipped,Amazon.in,NaN
142,ORD10143,30-07-2026,Amazon Coimbatore,CUST1039,Sneha,Water Bottle,Home,Coimbatore,South,4.0,699.0,0.0,2796,2796.00,Cash on Delivery,Delivered,Amazon Business,31-07-2026
143,ORD10144,04-07-2026,Amazon Chennai,CUST1037,Arun,Backpack,Bags,Chennai,South,3.0,1599.0,20.0,4797,3837.60,UPI,Cancelled,Amazon Business,06-07-2026
144,ORD10145,12-07-2026,Amazon Madurai,CUST1058,Karthik,Desk Lamp,Home,Madurai,South,1.0,1249.0,0.0,1249,1249.00,Cash on Delivery,Cancelled,Amazon Fresh,15-07-2026
145,ORD10146,03-08-2026,Amazon Delhi,CUST1007,Sneha,Power Bank,Electronics,Delhi,North,3.0,1899.0,25.0,5697,4272.75,Net Banking,Delivered,Amazon.in,04-08-2026
146,ORD10147,15-08-2026,Amazon Delhi,CUST1043,Priya,Webcam,Electronics,Delhi,North,5.0,2399.0,10.0,11995,10795.50,UPI,Delivered,Amazon.in,17-08-2026
147,ORD10148,05-07-2026,Amazon Chennai,CUST1009,Rahul,Pen Set,Stationery,Chennai,South,2.0,399.0,10.0,798,718.20,Net Banking,Delivered,Amazon.in,06-07-2026
148,ORD10149,17-07-2026,Amazon Trichy,CUST1032,Rahul,Monitor,Electronics,Trichy,South,3.0,12499.0,5.0,37497,35622.15,Cash on Delivery,Cancelled,Amazon Fresh,20-07-2026
149,ORD10150,03-08-2026,Amazon Madurai,CUST1041,Meena,Coffee Mug,Home,Madurai,South,1.0,499.0,15.0,499,424.15,Debit Card,Delivered,Amazon.in,06-08-2026
150,ORD10011,28-07-2026,Amazon Pune,CUST1008,Sneha,Power Bank,Electronics,Pune,West,2.0,1699.0,5.0,3398,3228.10,Credit Card,Delivered,Amazon Fresh,29-07-2026
151,ORD10026,05-07-2026,Amazon Bengaluru,CUST1032,Rahul,Power Bank,Electronics,Bengaluru,South,1.0,1849.0,25.0,1849,1386.75,UPI,Delivered,Amazon Fresh,10-07-2026
152,ORD10071,10-07-2026,Amazon Pune,CUST1017,Karthik,Power Bank,Electronics,Pune,West,5.0,1799.0,20.0,8995,7196.00,UPI,Returned,Amazon.in,13-07-2026

In [8]:
df.columns

Index(['Order ID', 'Order Date', 'Store / Seller', 'Customer ID',
       'Salesperson', 'Product', 'Category', 'City', 'Region', 'Quantity',
       'Unit Price', 'Discount %', 'Gross Amount', 'Sales Amount',
       'Payment Method', 'Order Status', 'Sales Channel', 'Ship Date'],
      dtype='str')

In [9]:
df.describe()

         Quantity    Unit Price  Discount %  Gross Amount  Sales Amount
count  151.000000    151.000000  152.000000    153.000000    153.000000
mean     2.867550   2447.013245   13.157895   6587.967320   5772.845752
std      1.472755   3388.450387    8.739880   9717.705304   8748.106448
min      1.000000     99.000000    0.000000    199.000000    179.100000
25%      1.500000    524.000000    5.000000   1398.000000   1123.500000
50%      3.000000   1399.000000   15.000000   3196.000000   2796.000000
75%      4.000000   2199.000000   20.000000   6796.000000   6070.500000
max      5.000000  12599.000000   25.000000  50196.000000  50196.000000

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        153 non-null    str
 1   Order Date      153 non-null    str
 2   Store / Seller  153 non-null    str
 3   Customer ID     150 non-null    str
 4   Salesperson     150 non-null    str
 5   Product         152 non-null    str
 6   Category        151 non-null    str
 7   City            151 non-null    str
 8   Region          150 non-null    str
 9   Quantity        151 non-null    float64
 10  Unit Price      151 non-null    float64
 11  Discount %      152 non-null    float64
 12  Gross Amount    153 non-null    int64
 13  Sales Amount    153 non-null    float64
 14  Payment Method  151 non-null    str
 15  Order Status    152 non-null    str
 16  Sales Channel   153 non-null    str
 17  Ship Date       151 non-null    str
dtypes: float64(4), int64(1), str(13)
memory usage: 39.1 KB

In [11]:
df.isnull()

,Order ID,Order Date,Store / Seller,Customer ID,Salesperson,Product,Category,City,Region,Quantity,Unit Price,Discount %,Gross Amount,Sales Amount,Payment Method,Order Status,Sales Channel,Ship Date
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
149,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
150,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
151,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
152,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [12]:
df.isnull().sum()

Order ID          0
Order Date        0
Store / Seller    0
Customer ID       3
Salesperson       3
Product           1
Category          2
City              2
Region            3
Quantity          2
Unit Price        2
Discount %        1
Gross Amount      0
Sales Amount      0
Payment Method    2
Order Status      1
Sales Channel     0
Ship Date         2
dtype: int64

In [13]:
df_ffill=df.copy()
df_ffill["Salesperson"]=df_ffill["Salesperson"].ffill()
print(df_ffill)

     Order ID  Order Date     Store / Seller Customer ID Salesperson  \
0    ORD10001  08-07-2026       Amazon Kochi    CUST1021       Vijay
1    ORD10002  22-07-2026  Amazon Coimbatore    CUST1002       Meena
2    ORD10003  12-07-2026   Amazon Bengaluru    CUST1022     Karthik
3    ORD10004  13-08-2026      Amazon Trichy    CUST1057       Rahul
4    ORD10005  25-07-2026        Amazon Pune    CUST1014       Priya
..        ...         ...                ...         ...         ...
148  ORD10149  17-07-2026      Amazon Trichy    CUST1032       Rahul
149  ORD10150  03-08-2026     Amazon Madurai    CUST1041       Meena
150  ORD10011  28-07-2026        Amazon Pune    CUST1008       Sneha
151  ORD10026  05-07-2026   Amazon Bengaluru    CUST1032       Rahul
152  ORD10071  10-07-2026        Amazon Pune    CUST1017     Karthik

                  Product     Category        City Region  Quantity  \
0          Wireless Mouse  Electronics       Kochi  South       4.0
1    Bluetooth Headphones  Electronics  Coimbatore  South       5.0
2            Laptop Stand       Office   Bengaluru  South       4.0
3             USB-C Cable  Electronics      Trichy  South       4.0
4     Mechanical Keyboard  Electronics        Pune   West       1.0
..                    ...          ...         ...    ...       ...
148               Monitor  Electronics      Trichy  South       3.0
149            Coffee Mug         Home     Madurai  South       1.0
150            Power Bank  Electronics        Pune   West       2.0
151            Power Bank  Electronics   Bengaluru  South       1.0
152            Power Bank  Electronics        Pune   West       5.0

     Unit Price  Discount %  Gross Amount  Sales Amount    Payment Method  \
0         799.0        20.0          3196       2556.80       Credit Card
1        1499.0        15.0          7495       6370.75       Net Banking
2        1199.0        20.0          4796       3836.80       Net Banking
3         499.0        15.0          1996       1696.60  Cash on Delivery
4        2549.0         5.0          2549       2421.55       Credit Card
..          ...         ...           ...           ...               ...
148     12499.0         5.0         37497      35622.15  Cash on Delivery
149       499.0        15.0           499        424.15        Debit Card
150      1699.0         5.0          3398       3228.10       Credit Card
151      1849.0        25.0          1849       1386.75               UPI
152      1799.0        20.0          8995       7196.00               UPI

    Order Status    Sales Channel   Ship Date
0      Delivered     Amazon Fresh  13-07-2026
1       Returned  Amazon Business  27-07-2026
2      Delivered        Amazon.in  14-07-2026
3      Delivered     Amazon Fresh  17-08-2026
4      Delivered  Amazon Business  29-07-2026
..           ...              ...         ...
148    Cancelled     Amazon Fresh  20-07-2026
149    Delivered        Amazon.in  06-08-2026
150    Delivered     Amazon Fresh  29-07-2026
151    Delivered     Amazon Fresh  10-07-2026
152     Returned        Amazon.in  13-07-2026

[153 rows x 18 columns]

In [14]:
df_bfill=df.copy()
df_bfill["Salesperson"]=df_bfill["Salesperson"].bfill()
print(df_bfill)

     Order ID  Order Date     Store / Seller Customer ID Salesperson  \
0    ORD10001  08-07-2026       Amazon Kochi    CUST1021       Vijay
1    ORD10002  22-07-2026  Amazon Coimbatore    CUST1002       Meena
2    ORD10003  12-07-2026   Amazon Bengaluru    CUST1022     Karthik
3    ORD10004  13-08-2026      Amazon Trichy    CUST1057       Rahul
4    ORD10005  25-07-2026        Amazon Pune    CUST1014       Priya
..        ...         ...                ...         ...         ...
148  ORD10149  17-07-2026      Amazon Trichy    CUST1032       Rahul
149  ORD10150  03-08-2026     Amazon Madurai    CUST1041       Meena
150  ORD10011  28-07-2026        Amazon Pune    CUST1008       Sneha
151  ORD10026  05-07-2026   Amazon Bengaluru    CUST1032       Rahul
152  ORD10071  10-07-2026        Amazon Pune    CUST1017     Karthik

                  Product     Category        City Region  Quantity  \
0          Wireless Mouse  Electronics       Kochi  South       4.0
1    Bluetooth Headphones  Electronics  Coimbatore  South       5.0
2            Laptop Stand       Office   Bengaluru  South       4.0
3             USB-C Cable  Electronics      Trichy  South       4.0
4     Mechanical Keyboard  Electronics        Pune   West       1.0
..                    ...          ...         ...    ...       ...
148               Monitor  Electronics      Trichy  South       3.0
149            Coffee Mug         Home     Madurai  South       1.0
150            Power Bank  Electronics        Pune   West       2.0
151            Power Bank  Electronics   Bengaluru  South       1.0
152            Power Bank  Electronics        Pune   West       5.0

     Unit Price  Discount %  Gross Amount  Sales Amount    Payment Method  \
0         799.0        20.0          3196       2556.80       Credit Card
1        1499.0        15.0          7495       6370.75       Net Banking
2        1199.0        20.0          4796       3836.80       Net Banking
3         499.0        15.0          1996       1696.60  Cash on Delivery
4        2549.0         5.0          2549       2421.55       Credit Card
..          ...         ...           ...           ...               ...
148     12499.0         5.0         37497      35622.15  Cash on Delivery
149       499.0        15.0           499        424.15        Debit Card
150      1699.0         5.0          3398       3228.10       Credit Card
151      1849.0        25.0          1849       1386.75               UPI
152      1799.0        20.0          8995       7196.00               UPI

    Order Status    Sales Channel   Ship Date
0      Delivered     Amazon Fresh  13-07-2026
1       Returned  Amazon Business  27-07-2026
2      Delivered        Amazon.in  14-07-2026
3      Delivered     Amazon Fresh  17-08-2026
4      Delivered  Amazon Business  29-07-2026
..           ...              ...         ...
148    Cancelled     Amazon Fresh  20-07-2026
149    Delivered        Amazon.in  06-08-2026
150    Delivered     Amazon Fresh  29-07-2026
151    Delivered     Amazon Fresh  10-07-2026
152     Returned        Amazon.in  13-07-2026

[153 rows x 18 columns]

In [15]:
df.isnull().sum()

Order ID          0
Order Date        0
Store / Seller    0
Customer ID       3
Salesperson       3
Product           1
Category          2
City              2
Region            3
Quantity          2
Unit Price        2
Discount %        1
Gross Amount      0
Sales Amount      0
Payment Method    2
Order Status      1
Sales Channel     0
Ship Date         2
dtype: int64

In [17]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
148    False
149    False
150     True
151     True
152     True
Length: 153, dtype: bool

In [18]:
df.duplicated().sum()

np.int64(3)

In [ ]:
df.drop_duplicates(inplace=True)

: